# .github/workflows/ci.yml
# Continuous Integration (CI) Workflow
name: ci

# This workflow will run whenever we push commits to the `main` branch, or
# whenever there's a pull request to the `main` branch. See:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#on

on:
    push:
        branches:
            - main

jobs:
    docker-build-push:
        name: 'Docker image build and Push to DockerHub'
    
        runs-on: ubuntu-latest

        steps:
        - name: Check out Code
          uses: actions/checkout@v4

        - name: Setup Deocker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            # Directly reference secrets and GitHub context variables in the tags
            tags: ${{ secrets.DOCKERHUB_REPO }}:sha-${{ github.sha }}, ${{ secrets.DOCKERHUB_REPO }}:main, ${{ secrets.DOCKERHUB_REPO }}:latest
            # Pass the SHA as a build argument to the Dockerfile
            build-args: |
                COMMIT_SHA=sha-${{ github.sha }}
                BUILD_DATE=${{ github.event.repository.updated_at }}
                NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
                NEXT_PUBLIC_AWS_COGNITO_AUTHORITY=${{ secrets.NEXT_PUBLIC_AWS_COGNITO_AUTHORITY }}
                NEXT_PUBLIC_AWS_COGNITO_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AWS_COGNITO_CLIENT_ID }}
                NEXT_PUBLIC_OAUTH_SIGN_IN_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_OAUTH_SIGN_IN_REDIRECT_URL }}
                NEXT_PUBLIC_OAUTH_SIGN_OUT_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_OAUTH_SIGN_OUT_REDIRECT_URL }}
                NEXT_PUBLIC_AWS_COGNITO_HOSTED_UI_DOMAIN=${{ secrets.NEXT_PUBLIC_AWS_COGNITO_HOSTED_UI_DOMAIN }}
